language: node_js
node_js:
  - "0.11"
  - "0.10"

matrix:
    allow_failures:
        - node_js: "0.11"

before_install: npm install -g grunt-cli
install: npm install
after_success:
    - npm run coveralls